spring:

  datasource:
    url: jdbc:mysql://localhost:3306/kokodo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    hibernate:
      ddl-auto: create
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
